exclude: 'build|data/datasets|data/scene_datasets|data/objects|src/deps|src/obsolete'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
    -   id: isort
        exclude: docs/
        additional_dependencies: [toml]

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      exclude: ^examples/tutorials/(nb_python|colabs)

-   repo: https://github.com/myint/autoflake
    rev: master
    hooks:
    -   id: autoflake
        args: ['--expand-star-imports', '--ignore-init-module-imports', '--in-place', '-c']
        exclude: docs/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        exclude: docs/
        additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions

-   repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
    -   id: nbstripout
        files: ".ipynb"

-   repo: local
    hooks:
    -   id: jupytext-sync
        name: Sync scripts and notebooks
        files: '^examples/tutorials/(colabs|nb_python)/(.*\.py|.*\.ipynb)$'
        entry: jupytext --update-metadata '{"jupytext":{"notebook_metadata_filter":"all", "cell_metadata_filter":"-all"}, "accelerator":"GPU"}' --set-formats 'nb_python//py:percent,colabs//ipynb' --pipe black --pipe "sed s/[[:space:]]*\#[[:space:]]\%\%/\#\%\%/g" --pipe 'isort -' --pipe-fmt 'py:percent' --sync
        pass_filenames: true
        additional_dependencies:
            - 'jupytext==1.5.2'
            - 'black==20.8b1'
            - 'isort==5.4.2'
        always_run: false
        language: python
        require_serial: true

-   repo: local
    hooks:
    - id: clang-format
      name: Run clang-format
      exclude: src/deps
      entry: clang-format -i -style=file
      types: [text]
      files: '.*\.(cpp|h|hpp|cu|cuh)$'
      language: system

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        exclude: (^src/(cmake/Find|deps)|configure\.h\.cmake$)

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.4.0
    hooks:
    -   id: eslint
        args: [--fix, --ext .html,.js]
        additional_dependencies:
        - eslint@6.4.0
        - eslint-config-prettier@6.3.0
        - eslint-plugin-prettier@3.1.0
        - eslint-plugin-html@6.0.0
        - prettier@1.18.2

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
    -   id: shellcheck
