exclude: 'build|src/deps|src/obsolete'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=2000']
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
    -   id: isort
        exclude: docs/
        additional_dependencies: [toml]

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      exclude: ^examples/tutorials/(nb_python|colabs)

-   repo: https://github.com/myint/autoflake
    rev: master
    hooks:
    -   id: autoflake
        args: ['--expand-star-imports', '--ignore-init-module-imports', '--in-place', '-c']
        exclude: docs/

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        exclude: docs/
        additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions

-   repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
    -   id: nbstripout
        files: ".ipynb"

-   repo: local
    hooks:
    -   id: jupytext-sync
        name: Sync scripts and notebooks
        files: '^examples/tutorials/(colabs|nb_python)/(.*\.py|.*\.ipynb)$'
        entry: jupytext --update-metadata '{"jupytext":{"notebook_metadata_filter":"all", "cell_metadata_filter":"-all"}, "accelerator":"GPU"}' --set-formats 'nb_python//py:percent,colabs//ipynb' --pipe black --pipe "sed s/[[:space:]]*\#[[:space:]]\%\%/\#\%\%/g"  --pipe 'isort -' --pipe-fmt 'py:percent' --sync
        pass_filenames: true
        additional_dependencies:
            - 'jupytext==1.5.2'
            - 'black==20.8b1'
            - 'isort==5.4.2'
        always_run: false
        language: python
