# ------------------------------------------------------------------------------
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
# ------------------------------------------------------------------------------
SIMULATOR:
  TYPE: Sim-v0
  AGENT_0:
    SENSORS: [DEPTH_SENSOR, RGB_SENSOR]
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  RGB_SENSOR:
    WIDTH: 224
    HEIGHT: 224
# ------------------------------------------------------------------------------
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 3.0
  SENSORS: [
    POINTGOAL_WITH_GPS_COMPASS_SENSOR,
    HEADING_SENSOR
  ]
  POINTGOAL_SENSOR:
    GOAL_FORMAT: POLAR
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: "pointgoal"
  POSSIBLE_ACTIONS: [
    STOP,
    MOVE_FORWARD,
    TURN_LEFT,
    TURN_RIGHT
  ]
  MEASUREMENTS: [
    DISTANCE_TO_GOAL,
    TOP_DOWN_MAP,
    SUCCESS,
  ]
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
# ------------------------------------------------------------------------------
DATASET:
  TYPE: PointNav-v1
  SPLIT: test
  DATA_PATH: habitat-lab/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz
  SCENES_DIR: habitat-lab/data/scene_datasets/
# ------------------------------------------------------------------------------
RL:
  ppo_checkpoint: "model_ckpt/ppo.pth"
  PPO: 
    clip_param: 0.1
    ppo_epoch: 4
    # This was 4 in the paper
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1.e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50
    use_normalized_advantage: False
# ------------------------------------------------------------------------------
MODEL:
  POLICY: "seq2seq"
  # on GT trajectories in the training set
  use_cpu: False
  inflection_weight_coef: 3.2
  ablate_depth: False
  ablate_rgb: False
  ablate_pointgoal: False
  RGB_ENCODER:
    cnn_type: "TorchVisionResNet50"
    output_size: 256
  DEPTH_ENCODER:
    # 'VlnResnetDepthEncoder' or 'SimpleDepthCNN'
    cnn_type: "VlnResnetDepthEncoder"
    output_size: 128
    # type of resnet to use
    backbone: "resnet50"
    # path to DDPPO resnet weights
    ddppo_checkpoint: "model_ckpt/depth_resnet50.pth"
  STATE_ENCODER:
    hidden_size: 512
    rnn_type: "GRU"
  SEQ2SEQ:
    use_prev_action: False
  PROGRESS_MONITOR:
    use: False
    alpha: 1.0  # loss multiplier
# ------------------------------------------------------------------------------
CONTROLLERS:
  use_fallback: True
  blackbox_id: "ppo_controller"
  fallback_id: "simple_unit_controller"
# ------------------------------------------------------------------------------
SIMULATOR_GPU_ID: 0
USE_CPU: False
TORCH_GPU_ID: 0
LOG_FILE: "rl_controller.log"
LOG_UPDATE: 1
NUM_EPISODES: 5
NUM_PROCESSES: 1
VIDEO_DIR: out/rl_controller/
VIDEO_OPTION: ["disk"]