# ------------------------------------------------------------------------------
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: True
# ------------------------------------------------------------------------------
SIMULATOR:
  TYPE: Sim-v0
  AGENT_0:
    SENSORS: [DEPTH_SENSOR, RGB_SENSOR]
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  RGB_SENSOR:
    WIDTH: 224
    HEIGHT: 224
# ------------------------------------------------------------------------------
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 3.0
  SENSORS: [
    POINTGOAL_WITH_GPS_COMPASS_SENSOR,
    HEADING_SENSOR
  ]
  POINTGOAL_SENSOR:
    GOAL_FORMAT: POLAR
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: "pointgoal"
  POSSIBLE_ACTIONS: [
    STOP,
    MOVE_FORWARD,
    TURN_LEFT,
    TURN_RIGHT
  ]
  MEASUREMENTS: [
    DISTANCE_TO_GOAL,
    TOP_DOWN_MAP,
    SUCCESS,
  ]
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
# ------------------------------------------------------------------------------
DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: habitat-lab/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz
  SCENES_DIR: habitat-lab/data/scene_datasets/
# ------------------------------------------------------------------------------
CONTROLLERS:
  blackbox_id: "simple_controller"
  fallback_id: "simple_unit_controller"
  use_fallback: True
# ------------------------------------------------------------------------------
SIMULATOR_GPU_ID: 0
USE_CPU: True
TORCH_GPU_ID: 0
LOG_FILE: "simple_controller.log"
LOG_UPDATE: 1
NUM_EPISODES: 5
NUM_PROCESSES: 1
VIDEO_DIR: out/simple_controller/
VIDEO_OPTION: ["disk"]